/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "server_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace container_service {


Req::~Req() throw() {
}


void Req::__set_uid(const int64_t val) {
  this->uid = val;
}

void Req::__set_cveName(const std::string& val) {
  this->cveName = val;
}

uint32_t Req::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->uid);
          this->__isset.uid = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->cveName);
          this->__isset.cveName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t Req::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("Req");

  xfer += oprot->writeFieldBegin("uid", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->uid);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("cveName", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->cveName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(Req &a, Req &b) {
  using ::std::swap;
  swap(a.uid, b.uid);
  swap(a.cveName, b.cveName);
  swap(a.__isset, b.__isset);
}

Req::Req(const Req& other0) {
  uid = other0.uid;
  cveName = other0.cveName;
  __isset = other0.__isset;
}
Req& Req::operator=(const Req& other1) {
  uid = other1.uid;
  cveName = other1.cveName;
  __isset = other1.__isset;
  return *this;
}
void Req::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "Req(";
  out << "uid=" << to_string(uid);
  out << ", " << "cveName=" << to_string(cveName);
  out << ")";
}

} // namespace
